#!/bin/bash

clear
cat <<'.'
 ______   _______  _______  _______  ___   ___      _______  _______ 
|      | |       ||       ||       ||   | |   |    |       ||       |
|  _    ||   _   ||_     _||    ___||   | |   |    |    ___||  _____|
| | |   ||  | |  |  |   |  |   |___ |   | |   |    |   |___ | |_____ 
| |_|   ||  |_|  |  |   |  |    ___||   | |   |___ |    ___||_____  |
|       ||       |  |   |  |   |    |   | |       ||   |___  _____| |
|______| |_______|  |___|  |___|    |___| |_______||_______||_______|
.
printf "                                                      made by arsyhiy\n"
printf "\n"
printf "=======================================================================\n"

# наверное надо перенести куда нибудь еще
cp config.env.template config.env

source ./utils.sh
CONFIG="config.env"
source "$CONFIG"

LOG_FILE="${LOG_FILE:-packages.log}"
> "$LOG_FILE"

any_flag_is_false() {
    source "$CONFIG"
    for flag in INSTALL CONFIG; do
        if [[ "${!flag}" == "false" ]]; then
            return 0
        fi
    done
    return 1
}

# need more helpfull name
while any_flag_is_false; do
    source "$CONFIG"

    # установка пакетов деибана, snap и flathub приложения
    # NOTE: обдумать название
    if [[ "$INSTALL" == "false" ]]; then
        # может что то получше echo
        echo "Installing Debian packages..."
        if ./install.sh; then
            set_flag_value INSTALL true
        else
            # что то получше echo
            echo "Error installing Debian packages" | tee -a "$LOG_FILE"
            set_flag_value INSTALL error
        fi
    elif [[ "$INSTALL" == "error" ]]; then
        # не echo
        echo "Skipping Debian packages (previous error)" | tee -a "$LOG_FILE"
    fi

    # config
    if [[ "$CONFIG" == "false" ]]; then
        # может что то получше echo
        echo "config is configin"
        if ./config.sh; then
            set_flag_value CONFIG true
        else
            # что то получше echo
            echo "Error config" | tee -a "$LOG_FILE"
            set_flag_value CONFIG error
        fi
    elif [[ "$CONFIG" == "error" ]]; then
        # не echo
        echo "Skipping config (previous error)" | tee -a "$LOG_FILE"
    fi

done

# ненавижу echo
echo "Setup finished. Check $LOG_FILE for details."







надо добавить куда нибудь
   ## python
   pipx --version || sudo apt install -y pipx
   pipx ensurepath
   sudo pipx ensurepath --global # optional to allow pipx actions with --global argument
   poetry --version || pipx install poetry # for sudo poetry i get : command not found and 100% trying installing every time.
	

   git clone https://github.com/arsyhiy/nvim.git ~/.config/nvim # it will not cloning if if directory already there. so it will cost not much.




    # zsh and plugins
    sudo apt install -y zsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
