# ─────────────────────────────
# GENERAL
# ─────────────────────────────

general {
    grab_focus = true
}


# ─────────────────────────────
# CACHE
# ─────────────────────────────

cache {
    enabled = true
}


# ─────────────────────────────
# FINDERS
# ─────────────────────────────

finders {
    default_finder = desktop

    desktop_prefix =
    unicode_prefix = .
    math_prefix = =
    font_prefix = '

    desktop_icons = true

    # If you use uwsm:
    # desktop_launch_prefix = uwsm app -- 
}


# ─────────────────────────────
# UI
# ─────────────────────────────

ui {
    window_size = 800 400
}
