# set 256 color
set -g default-terminal "screen-256color"

# main prefix
set -g prefix C-Space

# sorting by names 
bind  s choose-tree -sZ -O name

# change of indexes
set -g base-index 1
setw -g pane-base-index 1

# reload button
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
