set -g default-terminal "screen-256color"

# main prefix
set -g prefix C-Space

# sorting by names 
bind  s choose-tree -sZ -O name

# change of indexes
set -g base-index 1
setw -g pane-base-index 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# Plugins options
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum 'on'
set -g @continuum-restore 'on'

# Status bar
set -g status-bg "#85adad"
set -g status-interval 5

# TPM (always last)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm'"

run -b '~/.tmux/plugins/tpm/tpm'
